### ISSUE TITLE
Fire press action before click/touch is finished

### ISSUE THREAD

**Issue by niklasgrewe** [Rezi/svelte-gestures#12]
Hi, i want to customize the press action. So when i a user press on a button i want to show a modal **before** the action is finished. It is possible or do i need to implement my own gesture for this purpose? The Readme says: 

> Press action is fired only when the click/touch is finished after the give timeframe

Thanks for your answer

In the library [long-press-event](https://www.npmjs.com/package/long-press-event) this seems to be possible

**Comment by Rezi** [comment]
I can add it, but it would require some better description what do you want to achieve.
Is the desired solution that user can specify (by some option) whether event should wait for the press action to be finished or simply trigger after the time frame, does not matter whether the user continue holding it?

**Comment by niklasgrewe** [comment]
glad you can add the feature. For my case, it would be great if the event is triggered after the timeframe, not matter whether the user continue holding it. This is often the default behavior in apps. Maybe this could be set via an additional option like this:

```html
<div use:press={{ timeframe: 300, triggerBeforeFinished: true }} on:press={handler} style="width:500px;height:500px;border:1px solid black;">
  press: {x} {y}
</div>
```

**Comment by Rezi** [comment]
Here we go, `triggerBeforeFinished ` has been added to version 1.4.0 on press action.
Let me know if something does not works as it should ;)
enjoy!
