### ISSUE TITLE
Possible limitation, or I just don’t understand something

### ISSUE THREAD

**Issue by KocsisGabor** [Rezi/svelte-gestures#14]
This is a great library, thanks for sharing. However, in my use case I can't really use it, but maybe that's just because I don't understand something.   

In my case, I have to watch for pan events on multiple elements. One option I have is to put the pan action on a container and manipulate the elements based on the target of the event, but this is not really a good solution for me because all the targets are complex, it would simply be too much work.   
The other solution is to just place the action on each element individually. This works, but it doesn't do what I would do if I didn't use this library, because it only triggers the pointermove on the element itself.   

What I would do is attach a pointerdown event to the element I want to manipulate, and when that event is triggered, I would attach a pointermove event to the window so I can move outside the element.  
This library makes me attach the pointerdown and pointermove events to the same element, so I can't move outside of it.  

[Here is a repl which might help](https://svelte.dev/repl/4406bf6df75a42c4aa5fbd60b95ef29b?version=3.50.0) What I try to show in this repl is that the red box can not be moved outside of the grey box unless I attach the action only to the container in which case I need to deal with some unnecessary complexity. 

I plan to fork your library to change the setPointerControls function so it accepts another node as a target for up, move and similar events but that is hard work for me since I need to understand everything that depends on this function. I thought I first should just ask you: do you think this change is easily possible or do you see problems that will appear after I made this change?

**Comment by Rezi** [comment]
Sorry, but adding pan event on container is the right way to go. It is gesture library for a gesture recognition. You are probably looking rather for something like drag and drop. Or you simply need custom implementation. 
As there is none else requesting this king of feature I am closing the issue in favour of keeping the library small with a single purpose
