### ISSUE TITLE
Press event blocks scrolling on Android phone

### ISSUE THREAD

**Issue by roma-pashkovsky** [Rezi/svelte-gestures#15]
Hey Tomas, first of all thank you for the great project!

I've noticed that when I set up 'press'  listener on an item, it prevent scrolling within its parent container on the Android device. Do you have any ideas why that could happen?

That's my project https://k-garoo.fun/home/lists
If you open it on the phone, create a long list and try scrolling upon list items, it won't scroll. I've found that it's because there's a press handler on each list item.

**Comment by ilblog** [comment]
On iOS too. It blocks default action.

**Comment by Rezi** [comment]
Should be resolved in version 1.5
