### ISSUE TITLE
continuous swipe update

### ISSUE THREAD

**Issue by fhennig** [Rezi/svelte-gestures#17]
Hey! I've needed to get continuous swipe events, i.e. events _while_ the user is swiping, to move elements along as the user is moving their finger over the screen. I think, this is not possible with svelte-gestures if I'm not mistaken. A friend and I have ported the react-swipable library to svelte (https://github.com/react2svelte/swipeable) to do this (If you'd like to link to it, I'd be very happy :) )

I'm making this ticket to let you guys know that this functionality is quite useful and and implementation exists, I think maybe it would be nice to also merge it in here. If I find some time I might look into it, but if someone else is keen, feel free to take it! I think it would be great to have one place for anything swipe-releated, but the libraries should work fine next to each other as well!

**Comment by Rezi** [comment]
There is the PAN action for this
