### ISSUE TITLE
Add typescript based script tags

### ISSUE THREAD

**Issue by baseplate-admin** [Rezi/svelte-gestures#19]
Hi thanks for creating this awesome library. I was thinking maybe we should add types in the `README.MD` functions.

Specially to the code blocks.

EG : 

```html
<script>
  import { rotate } from 'svelte-gestures';
  let rotation;
  let x;
  let y;

  function handler(event) {
    rotation = event.detail.rotation;
    x = event.detail.center.x;
    y = event.detail.center.y;
  }
</script>
<div
  use:rotate
  on:rotate="{handler}"
  style="width:500px;height:500px;border:1px solid black;"
>
  rotation: {rotation} <br />
  center: x {x}, y {y}
</div>
```

This can be converted to typescript

---

## Why ? 

I cant seem to figure out how to type hint `swipe_handler` in the code below : 

```typescript
 const swipe_handler  = (event: CustomEvent) => {
        const direction = event.detail.direction;
        if (direction === "left") {
            // Do something
        } else if (direction === "right") {
             // Do something else ?
        }
    };
```

---

Once again thanks for creating this awesome library

**Comment by Webifi** [comment]
I think I'm having a similar issue.  I can't figure out how to use the following example with typescript:
https://svelte.dev/repl/c56082d9d056460d80e53cd71efddefe

**Comment by Rezi** [comment]
I'll try to add them. I am in favour of typescript. Unfortunately REPL does not support typescript and I just copied the same code I wrote in REPL. But as long I point to the REPL with link, the code in docs can easily be in TS.. Good point

**Comment by pupubird** [comment]
Can't wait for the typescript support!

**Comment by Rezi** [comment]
Types are now supported in version 5, please follow the documentation
