### ISSUE TITLE
Swipe not working on svelteKit

### ISSUE THREAD

**Issue by louislugas** [Rezi/svelte-gestures#20]
I tried in my svelte REPL, and it works really well. But when I copied it to my svelteKit project, it didn't work because my canvas suddenly had the styling `{ touch-action:none; user-select:none; }` even though I didn't add those. I solve it by adding `{ touch-action:auto !important; user-select:auto !important; pointer-events: all }`, and it works well with the `tap` gesture. But the `swipe` gesture is still off.

Then I reread the docs and found this
```
if you use the Svelte kit, you already have a global.d.ts in src folder. Just add this line after

/// <reference types="@sveltejs/kit" />

It must be done this way as language tools use global types and a regular npm package cannot expose global types as long as it is used by another package.
```

I'm confused because I don't have `global.d.ts` in src folder, but `app.d.ts` instead. And this is what my `app.d.ts` looks like:
```
// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface Platform {}
	}
}

export {};
```

Since I'm no expert in ts, I don't know where to put `/// <reference types="@sveltejs/kit" />` Is it with or without the `///`?

EDIT:
I've put it like this inside the app.d.ts (I don't have global.d.ts as stated above), and it looks like this:
```
// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface Platform {}
	}
}

export {};

/// <reference types="@sveltejs/kit" />
```

And still doesn't solve my problem

nb: this only occurs in the mobile mode, in the desktop, the "swipe" work if I swipe with my mouse.

**Comment by ValeraKvip** [comment]
Yes. This happens when you have a child element that can scroll (css:overflow). On the desktop, you scroll with the scrollbar, but on mobile devices, you scroll with the drag. And this is where this unpleasant problem comes in.

The solution is to add this option to the element:
`pointer-events: none;`
or do
`overflow: hidden;`

And control the scroll through this library.

**Comment by tosinek** [comment]
Something weird is going on here. When I use `overflow-x: hidden`, it behaves weird (doesn't work in SvelteKit, but in REPL it works in the browser but not on a phone). If you use just `overflow: hidden`, it works fine everywhere.
Example https://svelte.dev/repl/710e47eb0f504821abd9c8e07664be42?version=4.2.3

**Comment by Rezi** [comment]
This need to be handled with touch actions or pointer events as stated above, there is no magical solution which can be handled directly by this small library.
