### ISSUE TITLE
Types for Svelte 4

### ISSUE THREAD

**Issue by ngaer** [Rezi/svelte-gestures#22]
Typing namespace was renamed from `svelte.JSX` to `svelteHTML` in Svelte 4 (https://svelte.dev/docs/v4-migration-guide#other-breaking-changes). Would be nice to release a new version that supports types for Svelte 4.

**Comment by saint-james-fr** [comment]
Ok... so that's the reason why referencing the types still trigger an error, like using on:swipe. That would be great indeed.

**Comment by Rezi** [comment]
Resolved inversion 4.0.0
