### ISSUE TITLE
Handle the end of pinch operation

### ISSUE THREAD

**Issue by todkuro** [Rezi/svelte-gestures#24]
Is it possible to get the end of a pinch operation using only on:pinch?
I am currently using on:pinch and on:pointerup at the same time, and looking at the on:pointerup event to determine that on:pinch has ended.
It would be great if this could be done in a smarter way.

**Comment by Rezi** [comment]
there is an event handler `on:pinchup`, `on:pinchdown` and `on:pinchmove` you should use those.
