### ISSUE TITLE
5.0.3 Types issues

### ISSUE THREAD

**Issue by forexknight** [Rezi/svelte-gestures#27]
Hi Mate,
I recently updated gestures from 5.0.1 to 5.0.3.
When svelte type check is being processed I got the following type errors from your package:
 

> `/__w//node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/pan.ts:52:29
Error: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'. 
          new CustomEvent<PanPointerEventDetail>(gestureName, {
            detail: { x, y, target },
          })
/__w/E/node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/press.ts:69:13
Error: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'. 
            y,
            target: event.target,
            pointerType: event.pointerType,
/__w//node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/detector.ts:237:15
Error: Argument of type 'Coord | undefined' is not assignable to parameter of type 'Coord'.
  Type 'undefined' is not assignable to type 'Coord'. 
              strokeRotated.points,
              strokeRotated.center
            )
/__w//node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/detector.ts:243:15
Error: Argument of type 'Coord | undefined' is not assignable to parameter of type 'Coord'.
  Type 'undefined' is not assignable to type 'Coord'. 
              strokeUnrotated.points,
              strokeUnrotated.center
            );
/__w//node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/shapeGesture.ts:81:41
Error: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'. 
        new CustomEvent<ShapePointerEventDetail>(gestureName, {
          detail: { ...detectionResult, target },
        })
/__w//node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/swipe.ts:76:34
Error: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'. 
          new CustomEvent<SwipePointerEventDetail>(gestureName, {
            detail: { direction, target },
          })
/__w//node_modules/.pnpm/svelte-gestures@5.0.3/node_modules/svelte-gestures/src/tap.ts:49:27
Error: Type 'EventTarget | null' is not assignable to type 'EventTarget'.
  Type 'null' is not assignable to type 'EventTarget'. 
        new CustomEvent<TapPointerEventDetail>(gestureName, {
          detail: { x, y, target: event.target },
        })
`

Could you look at it?

**Comment by Rezi** [comment]
Resolved. With embarrassment and my own surprise I have to say strictNullChecks were not set to true in svelte-gestures, which led to ignoring possibility of event target being `null`. Now very few affected types are fixed. In version 5.0.4 there should be no such an error.

**Comment by forexknight** [comment]
thx ✅
