### ISSUE TITLE
[Chrome] Gesture over scrollable container inside wrapper not detected

### ISSUE THREAD

**Issue by SachsenspieltCoding** [Rezi/svelte-gestures#28]
> [!NOTE]
> **System Information**
> Browser: Chromium 127.0.6533.88 (Mobile view via. device toolbar)
> OS: Zorin OS 17.1

If you have a scrollable container inside another div, svelte-gestures will not be able to track any horizontal gestures (probably others too) over it when using Chrome/Chromium in the mobile version or with a mobile device selected in the desktop version.

## Reproduction

```svelte
<div use:swipe={{ timeframe: 300, minSwipeDistance: 60, touchAction: "pan-y" }} on:swipe={handler}>
    <div class="container">
        ...
    </div>
</div>

<style>
    .container {
	max-height: 200px;
	overflow-y: auto;
	overflow-x: hidden;
    }
</style>
```

Now when I try to do a swipe gesture over the container div, the swipe handler isn't triggered.

## Sveltelab Demo

https://www.sveltelab.dev/3i94xmx98u4meuw

## Svelte REPL Demo

https://svelte.dev/repl/635983d18f2841d3a962d5f749201b07?version=4.2.18

**Comment by Rezi** [comment]
This is how js event bubbling works. Your container with scrolling captures all the pointer move events and they never reach the gesture element. 
You are trying something what simply cannot work. You cannot scroll up and down and capture top, button gestures at the same time. You can implement scroll event listener and measure whether user scrolls up or down, because that's what you are apparently trying to do. 
Please read the documentation. There is composed gesture example integrating special custom scroll gesture. This  way you can do some extra handling, which DOM is not able to handle on its own.

**Comment by SachsenspieltCoding** [comment]
I forgot to mention, that it does work on other browsers like Firefox, Safari or Chrome Desktop.

That is why I opened this issue, because I found this behaviour strange.

**Comment by Rezi** [comment]
Desktop browsers does not scroll by swiping screen, that's probably why you see this differece

**Comment by SachsenspieltCoding** [comment]
But it works on Firefox/Safari mobile too.

Nevertheless, I think you might misunderstood my issue. I don't track vertical gestures which indeed collide with the scrolling.
Pan-y is used, as your documentation tells, for left and right swipe gestures.

**Comment by SachsenspieltCoding** [comment]
Oh, my fault. It has to be pan-x right?

**Comment by Rezi** [comment]
I'll need investigate why it worked on safari and Firefox it should not work there as well

**Comment by SachsenspieltCoding** [comment]
Hey @Rezi,
are there any news regarding your investigation?

**Comment by Rezi** [comment]
I tried firefox. And it does not work there as well. As expected. So I don't see any bug or unexpected behaviour. If you want to scroll and recognise gestures at the same time, please follow documentation in a readme. 
If you want to recognize left and right while keep vertical scrolling, just add touch-action: pan-y; to your .container CSS class.

**Comment by SachsenspieltCoding** [comment]
>If you want to recognize left and right while keep vertical scrolling, just add touch-action: pan-y; to your .container CSS class. This way horizontal gestures will be allowed to bubble up

That fixed my problem, thanks for your help!
