### ISSUE TITLE
No type intellisense

### ISSUE THREAD

**Issue by archimede67** [Rezi/svelte-gestures#3]
I am currently using svelte-gestures in a typescript project, and I do not have any sort of intellisense for its types, as my editor says that it "implicitly has an 'any' type" when importing.

I looked a bit and found that in `package.json` the types should be defined in `dist/svelteGestures.d.ts` but there is no such file in that directory.

Maybe this is why the types cannot be found?

**Comment by Rezi** [comment]
Sorry for inconvenience, it should be fixed now. 
Let me know if it works with version 1.2.2

**Comment by archimede67** [comment]
It does work !
Thank you
