### ISSUE TITLE
Press on mobile

### ISSUE THREAD

**Issue by thoward27** [Rezi/svelte-gestures#6]
Hey there! Thanks for this awesome project. 

Out of curiosity, is there an easy way to get the `press` event to work on mobile? I cannot seem to figure out how to get that to take precedence over the context menu.

Any tips/tricks would be greatly appreciated!

**Comment by Rezi** [comment]
Hi, good to hear you like it. I guess I need to add event modifiers option to the core events. I'll add support for that. Just need to figure out some nice way how to do it, so it can be granular per event. I'll try to do it in next few days. 
Btw what mobile/browser do you use? It can help with replication.
Thx for feedback

**Comment by thoward27** [comment]
Hey @Rezi, I am using chrome on android, project is here: https://github.com/thoward27/thor. 

Some extra details as I have continued to test this:

1. The `press` event *does* work actually, it's just super finicky. If I press too long, I get the context menu, not long enough, the event doesn't fire. I think this boils down to my needing to add some animations to inform the user better.
2. Unfortunately, it appears to break scrolling. If I drag my finger across the screen starting from any of my elements with the `press` event, nothing happens. If I drag my finger off the cards, scrolling works as expected.

**Comment by csellis** [comment]
@thoward27 I had to disable on iPad with this
https://bencollier.net/2010/04/disabling-hold-to-copy-on-mobile-safari/

**Comment by Rezi** [comment]
I tried to add the `style.userSelect = 'none';` as proposed by csellis from inside the directive. I also added preventDefault on contextmenu action which I encountered on windows touch. 
It has been release recently under version 1.3.2
@thoward27 Please let me know if it helped
