### ISSUE TITLE
Wrong direction with  touchAction: 'pan-y'

### ISSUE THREAD

**Issue by yamatoiizuka** [Rezi/svelte-gestures#7]
Hi, thanks for this great project!

I’m trying to use swipe with `touchAction: 'pan-y'`, but when scrolling to top/bottom with a smartphone, the swipe direction often shows `left`…

here is a example: https://7l1h1.csb.app/
a capture of the example: https://gyazo.com/8964aa342839cd6ae041330b23029302
the example source (code sand box): https://codesandbox.io/s/swipe-test-7l1h1?file=/Swipe.svelte:218-238

Any advice would be appreciated!

**Comment by Rezi** [comment]
Hi Yamatoiizuka, thanks for detailed report. I wish all reports were like yours. I found the bug, next version will be deployed shortly

**Comment by Rezi** [comment]
Fix should be out in version 1.3.2 
Please try it and let me know whether I can close this issue ;)

**Comment by yamatoiizuka** [comment]
Thanks for the fix! 
I tried version 1.3.2, and it’s perfectly working!
Could you close this issue? thank you!
