### ISSUE TITLE
sveltekit compatibility?

### ISSUE THREAD

**Issue by sharu725** [Rezi/svelte-gestures#9]
Looks like we cannot use it directly in Sveltekit. It would be great if it is compatible.

**Comment by Rezi** [comment]
It has been working with sveltekit. I'll try it with the latest version. Perhaps there are some breaking changes in new beta version. I'll be back soon with response / fix.

**Comment by Rezi** [comment]
I have just installed latest version od svelte kit and installed svelte gestures into it, it worked flawlessly. Looks like the issue is on your side. If there is some specific error, please create a repl with it and I can fix it then

**Comment by sharu725** [comment]
> I have just installed latest version od svelte kit and installed svelte gestures into it, it worked flawlessly. Looks like the issue is on your side. If there is some specific error, please create a repl with it and I can fix it then

It does work on a new project!
Could be something wrong on my setup. Thanks for testing.
